import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import SessionProviderWrapper from "./SessionProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PixHorizon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionProviderWrapper>
        <body className={inter.className}>
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        </body>
      </SessionProviderWrapper>
    </html>
  );
}
